// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package org.example;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class hello extends org.example.presets.HelloPreset {
    static { Loader.load(); }

// Parsed from <myhello.h>

// file: src/main/cpp/myhello.h
// #ifndef MYHELLO_H
// #define MYHELLO_H

public static native void printHelloWorld2();

// #endif // MYHELLO_H


}
